language: node_js
node_js:
  - "12"
addons:
  chrome: stable
sudo: true
before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- -- version 0.23.2
  - export PATH="$HOME/.yarn/bin:$PATH"
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
