version: 2.1 # use CircleCI 2.1
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/zch-ui # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:10.16.0 # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: install-yarn
          command: 'curl -o- -L https://yarnpkg.com/install.sh | bash -s -- -- version 1.19.1'
      - run:
          name: add-yarn
          command: 'export PATH="$HOME/.yarn/bin:$PATH"'
      - run:
          name: yarn-install
          command: yarn install
      - run: # run tests
          name: test
          command: yarn test
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples